name: deploy_aks
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: test
        run: env
      - name: Terraform Init Istio
        run: terraform init
      - name: Terraform Format Istio
        run: terraform fmt -check
      - name: Terraform Plan Istio
        run: terraform plan -input=false -var="config_path=$KUBE_CONFIG_PATH"
      - name: Terraform Deploy Istio
        run: terraform apply -auto-approve -input=false